:_content-type: PROCEDURE

[id="deploying-an-application-to-a-bare-metal-installation_{context}"]
= Building and deploying an application to a bare metal installation

[role="_abstract"]
You can deploy an application to {ProductShortname} by using the {ProductShortname} deploy plug-in.

include::fragments/frag_application-home-info.adoc[]

.Prerequisites

* You have created an application.
+
For more information, see xref:developing-a-hello-world-servlet-application_default[Developing applications for {ProductShortName}].
* {ProductShortname} is running.

.Procedure

. Navigate to the _<application_home>_ directory.

. Add the following build configuration to the `pom.xml` configuration file in the `<project>` section to define the application archive filename.
+
[source,xml,options="nowrap"]
----
<build>
    ...
    <finalName>${project.artifactId}</finalName>        <!--1-->
</build>
----
<1> Set the name of the deployment to the project's artifact ID.

. Build and deploy the application by using the {ProductShortName} deploy plug-in.
+
[source,options="nowrap"]
----
$ mvn package wildfly:deploy
----

.Verification

* To access the application, navigate to the address `http://localhost:8080/_<project_name>_` in a browser.
+
You are redirected to the URL you configured in your applications' `index.html` file, and you get the following message:
+
----
Hello World!
----

[role="_additional-resources"]
.Next steps
* xref:testing-an-application-deployed-to-server_default[Testing an application deployed on {ProductShortName}]

