:_newdoc-version: 2.15.0
:_template-generated: 2023-10-16
:_mod-docs-content-type: PROCEDURE

[id="deploying-an-application-to-server-on-openshift-with-helm_{context}"]
= Building and deploying an application to {ProductShortname} on OpenShift with Helm

[role="_abstract"]
Use the {ProductShortname} Helm chart to configure and deploy application to {ProductShortname} on OpenShift with Helm.

.Prerequisites

* You have prepared your application for deployment on {cloudPlatform}.
+
For more information, see xref:preparing-an-application-for-deployment-on-openshift_deploying-an-application-to-cloudplatform[Preparing an application for deployment on OpenShift Container Platform].

include::fragments/frag_deploying-application-to-server-cloudplatform-common.adoc[]

. To access the application, navigate to the following address in a browser:
+
`http://_<APPLICATION_URL>_/helloworld` 
+
Replacing _<APPLICATION_URL>_ with its value that is printed in the output of the command.
+
You are redirected to http://_<APPLICATION_URL>_/helloworld/HelloWorld and you get the following message:
+
----
Hello World!
----

[role="_additional-resources"]
.Next steps
* xref:testing-an-application-deployed-to-server_default[Testing an application deployed on {ProductShortName}]
