////
Bootable jar is only included in hello world servlet application as of now.
Therefore, information related to bootable jar is included inside ifeval, which checks whether the artifact id matches that of the hello world servlet.
////

.Procedure

. Navigate to the __<application_home>__ directory.

ifeval::["{artifactID}" == "helloworld"]
. Create a profiles "provisioned-server", and "bootable-jar" in the `pom.xml` configuration file. These profiles configure the {ProductShortName} Maven plug-in for provisioning of a server with the application deployed.
+
[source,xml,options="nowrap",subs="attributes+"]
----
include::../sources/provisioned-server-profile.xml[]
----
<1> Provision the server with the application deployed in the `target/server` directory. 
<2> Use link:https://github.com/wildfly/wildfly-glow[WildFly Glow] to discover the feature packs and layers required to run the application, and provisions a server containing those layers.
<3> Provision and package the server with the application deployed as an executable jar.
<4> Use link:https://github.com/wildfly/wildfly-glow[WildFly Glow] to discover the feature packs and layers required to run the application, and provisions a server containing those layers.
endif::[]
+
ifeval::["{artifactID}" != "helloworld"]
[source,xml,options="nowrap",subs="attributes+"]
----
include::../sources/provisioned-server-profile-no-bootable.xml[]
----
<1> Provision the server with the application deployed in the `target/server` directory. 
<2> Use link:https://github.com/wildfly/wildfly-glow[WildFly Glow] to discover the feature packs and layers required to run the application, and provisions a server containing those layers.
endif::[]
+

. Define the application archive filename in the `<build>` section of `<project>` if you have not already defined it.
+
[source,xml,options="nowrap"]
----
<build>
    ...
    <finalName>${project.artifactId}</finalName>        <!--1-->
</build>
----
<1> Set the name of the deployment to the project's artifact ID.

. Provision the server with the application deployed.
+
[source,options="nowrap"]
----
$ mvn clean package
----

. Start the server.

** To start the {ProductShortName} provisioned server based on the "provisioned-server" profile, use the {ProductShortName} Maven plug-in `start` goal.
+
[source,options="nowrap"]
----
$ mvn wildfly:start
----

ifeval::["{artifactID}" == "helloworld"]
** To start the {ProductShortName} provisioned server based on the "bootable-jar" profile, use the {ProductShortName} Maven plug-in `start` goal.
+
[source,options="nowrap"]
----
$ mvn wildfly:start-jar
----
+
Alternatively, you can start the server without using Maven.
+
[source,options="nowrap"]
----
$ java -jar target/helloworld-bootable.jar
----
endif::[]
