.Procedure

. Move the application to your local Git repository, if it already is not in it.
+
[source,options="nowrap",subs=+quotes]
----
$ mv -r helloworld/ __<your_git_repo>__
----

. Create a profile "openshift" in the `pom.xml` configuration file.
+
This profile configures the {ProductShortName} maven plug-in, with respect to deployment on {cloudPlatform}.
+
[source,xml,options="nowrap",subs="attributes+"]
----
include::../sources/openshift-profile.xml[]
----
<1> `{wildflyMavenPluginArtifactID}` is a {ProductShortName} plug-in for provisioning a {ProductShortName} instance, with the application deployed on {cloudPlatform}.
<2> Use link:https://github.com/wildfly/wildfly-glow[WildFly Glow] to discover the feature packs and layers required to run the application, and provisions a server containing those layers.
<3> Prevent building of Java Archive (jar) files to decrease the build time and save disk space.

. Verify that the applications compiles.
+
[source,options="nowrap"]
----
$ mvn package -Popenshift
----

. Clean the project so that the project contains only the sources.
+
[source,options="nowrap"]
----
$ mvn clean
----

. Push the changes to your repository.
