.Procedure

. Navigate to the __<application_home>__ directory.

. Create a profile "provisioned-server" in the `pom.xml` configuration file.
+
This profile configures the {ProductShortName} Maven plug-in, with respect to the provisioning of a server with the application deployed.
+
[source,xml,options="nowrap",subs="attributes+"]
----
include::../sources/provisioned-server-profile.xml[]
----
<1> `feature-packs` defines the feature-packs. Feature packs  are zip archive files that contains features to dynamically provision a server. In our case all the features we need are provided by the standard {ProductShortName} pack `org.wildfly:wildfly-galleon-pack`.
<2> `layers` defines the layers from the configured feature-packs to include in the provisioned server. Each layer identifies one or more server capabilities that can be installed on its own, or in combination with other layers. In our case we opt for the cloud-server layer, which provisions just the basic features of {ProductShortName}, well suited for a cloud server.
<3> `<name>ROOT.war</name>`: Defines the resulting name of the application's web archive (WAR). If `ROOT.war` is specified then the application is deployed at the root path of the server, otherwise it is deployed at `<name/>` relative path.

. Build and deploy the application by using the {ProductShortName} deploy plug-in.
+
[source,options="nowrap"]
----
$ mvn package -Pprovisioned-server
----
+
You should see the following output:
+
----
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
----
